config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'static_pages/contact'

  get 'static_pages/about'

  root 'static_pages#landing_page'

  
end




 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
	end

	def show
	end

	def new
	end

	def create
	end

	def destroy
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
   def landing_page
   	@featured_product = product.first
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/star_pages_helper.rb
module StarPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fridge</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="page-wrap">
    	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container anchor" id="process">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="logo navbar-brand">
              <a href="#">Charlotte</a>
            </div><!--end of Charlotte-->

            <div class="navbar-header">
              </div> <!--end navbar-header -->
              </div><!--end logo navbar-brand-->
            <div class="navbar-collapse collapse">

        		<ul class="nav navbar-nav navbar-right">
        			<li><a href="https://secret-shore-73567.herokuapp.com/products">Home</a></li>
        			<li><a href="#">Recipes</a></li>
        			<li><a href="#">Chefs</a></li>
              <li><a href="#">Contact</a></li>
        		</ul>
          </div><!--end collapse-->
        </div><!--end continer anchor-->
      </nav><!--end of navbar-->

    <div class=block>
    </div>

         <%= yield %>
    </div><!--end of wrap-->

    <footer class="site-footer">
        <p>&copy; Charlotte Yandell 2017</p>
        <div class="twitter">
         <a href="https://twitter.com/Char_Brighton" class="twitter-follow-button" data-show-count="false">Follow @Char_Brighton</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div><!--end Twitter

        <!-- FB like button -->
        <div id="facebookButton">
          <div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="200" data-layout="button" data-action="like" data-size="small" data-show-faces="false" data-share="true"></a>
          </div><!-- / end facebookButton -->
        </div>
    </footer>
      
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
  <%= f.label :colour %><br>
  <%= f.text_field :colour %>
  </div>

  <div class="field">
  <%= f.label :price %><br>
  <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>


<div class="container-fluid">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-2 col-md-4">
        <%= image_tag("smeg.jpg", class: "img-responsive") %>
        <h1><%= product.name %></h1>
        <p><%= product.description %></p>
        <strong><%= product.price %></strong>
      </div><!--end col-->
    <% end %>
  </div><!--end row--> 
</div><!--end container-fluid"-->


<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price%>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
 

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>
<h1>Background of Blue Fridge</h1>
<h2>It can be a challenge to find healthy meal recipes with a limited amount of ingredients, use the the Blue Fridge app to enter what you have in your fridge and find recipes with a minimal amount of extra ingredients.  
</h2>
<%= image_tag("stars_small.jpg") %>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>
<h1>Blue Fridge</h1>
<h2>Charl is interested in helping other people with a busy routine create healthy recipes at home</h2>
<%= image_tag("stars_small.jpg") %>

app/views/static_pages/index.html.erb
  <h1>Welcome to the Blue Fridge</h1>
  <%= image_tag("spag.jpg", class: "fridge img-responsive") %>
	<h3><em>Delicious recipes for busy people</em></h3>

 
<div class="row">
  <div class="col-md-4 col-xs-12">
    <div class="gallery">
      <%= image_tag("veg.jpg", class: "img-responsive")%>
    </div><!--close gallery-->
    <h3>Beetroot</h3>
    <p>Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion
    daikon amaranth tatsoi tomatillo melon azuki bean garlic. Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.</p>
    </div> <!--end col-->

    <div class="col-md-4 col-xs-12">
      <div class="gallery">
        <%= image_tag("pasta.jpg", class: "img-responsive")%>
      </div> <!--close gallery-->
      <h3>Artichoke</h3>
      <p>Lotus root water spinach fennel kombu maize bamboo shoot green bean swiss chard seakale pumpkin onion chickpea gram corn pea. Brussels sprout coriander water chestnut gourd swiss chard wakame kohlrabi beetroot carrot watercress. Corn amaranth salsify bunya nuts nori azuki bean chickweed potato bell pepper artichoke
      </p>
    </div> <!--end col-->

    <div class="col-md-4 col-xs-12">
      <div class="gallery">
        <%= image_tag("cake.jpg", class: "img-responsive")%>
      </div> <!--close gallery-->
      <h3>Pumpkin</h3>
      <p>Turnip greens yarrow ricebean rutabaga endive cauliflower sea lettuce kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter purslane kale. Celery potato scallion desert raisin horseradish spinach carrot soko.</p>
    </div> <!--end col-->
</div><!--end row-->

app/views/static_pages/landing_page.html.erb
<h2>Featured Product:</h2>
<%= @featured_product.name %>